

# AWS SES
aws.ses.region=${AWS_REGION:sa-east-1}
aws.ses.sender=${AWS_SES_SENDER}
aws.ses.endpoint=${AWS_SES_ENDPOINT:http://localhost:4566}
aws.accessKeyId=${AWS_ACCESS_KEY_ID:test}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:test}