rate-limits.default-rule.path=/api
rate-limits.default-rule.capacity=100
rate-limits.default-rule.refill-interval=1

rate-limits.routes[0].path=/api/v1/auth/login
rate-limits.routes[0].capacity=5
rate-limits.routes[0].refill-interval=5

rate-limits.routes[1].path=/api/v1/auth/generate-password
rate-limits.routes[1].capacity=5
rate-limits.routes[1].refill-interval=10