## Rate Limiter
resilience4j.ratelimiter.metrics.enabled=true
### Login
resilience4j.ratelimiter.instances.loginRateLimiter.limitForPeriod=5
resilience4j.ratelimiter.instances.loginRateLimiter.limitRefreshPeriod=1m
resilience4j.ratelimiter.instances.loginRateLimiter.timeoutDuration=0
resilience4j.ratelimiter.instances.loginRateLimiter.register-health-indicator=true

### Generate Password
resilience4j.ratelimiter.instances.generatePasswordRateLimiter.limitForPeriod=3
resilience4j.ratelimiter.instances.generatePasswordRateLimiter.limitRefreshPeriod=30s
resilience4j.ratelimiter.instances.generatePasswordRateLimiter.timeoutDuration=0
resilience4j.ratelimiter.instances.generatePasswordRateLimiter.register-health-indicator=false