CREATE SCHEMA IF NOT EXISTS WEBSOCKET;

CREATE TABLE WEBSOCKET.users (
    id BIGINT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(70) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    deleted BOOLEAN DEFAULT FALSE,
    phone VARCHAR(20) UNIQUE NOT NULL,
    avatar VARCHAR(255) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (CHAR_LENGTH(name) >= 3)
);

CREATE TABLE WEBSOCKET.user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(10) NOT NULL DEFAULT 'USER',
    CONSTRAINT fk_user_roles FOREIGN KEY (user_id) REFERENCES WEBSOCKET.users (id) ON DELETE CASCADE,
    UNIQUE (user_id, role)
);